// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://djdqaavvkmsfbigtxupx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqZHFhYXZ2a21zZmJpZ3R4dXB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3ODEzNjgsImV4cCI6MjA2OTM1NzM2OH0.y8ec4PYs30N7iWDCrf5hHNgBmx81QtoGGiWMPP-3G50";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);